name: Newman run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dir for report
        run: 
          mkdir testArtifacts

      - name: install newman
        run:
          npm install uuid@latest
          yarn add uuid@latest
          npm install har-validator@latest
          npm install @faker-js/faker@latest
          pnpm add uuid@latest
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Test
        run: newman run ServerRest.postman_collection.json -e serverRest_env.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: newman
